language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; else phpenv config-add travis.php.ini; fi
  - composer self-update
  - composer update --prefer-source

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token:
      secure: I63bS1v5CFtuaWlLix2B+Gp/9P7c2K+F4HIwQVJgosb0pXswuUFNTVDPUdVlMk0lrdwMKXKrzY9CWFSWTGg5lkGMzYTT8EFwbodUjfgufoLw+NpwdnFfYW0WgfH8jpJdf/Z4MA/Bei5bk299hx53sF1NL7x3JuPgwLR2Vb62zj0=
